---
resources:
  - certificate.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml

namespace: development

commonLabels:
  env: development

secretGenerator:
  - name: api-secrets
    env: api-secrets.env
