---
resources:
  - backup_pvc.yaml
  - namespace.yaml
  - rabbitmq.yaml
  - backup_cronjob.yaml
  - postgresql.yaml

namespace: development

commonLabels:
  env: development

secretGenerator:
  - name: api-secrets
    env: api-secrets.env
