---
resources:
  - certificate.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml

namespace: development

commonLabels:
  env: development
  app: api


secretGenerator:
  - name: api-secrets
    envs:
      - api-secrets.env
