apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.admin.bootifulpodcast.online.
  labels:
    app: api
  name: api
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: api
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  api
  name:  api
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  api
  template:
    metadata:
      labels:
        app:  api
    spec:
      containers:
        - envFrom:
            - secretRef:
                name:  api-secrets
          image: gcr.io/pgtm-jlong/api:latest
          imagePullPolicy: Always
          name: api