name: Bootiful Podcast API Deploy

env:
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  BP_RABBITMQ_MANAGEMENT_PASSWORD: ${{ secrets.BP_RABBITMQ_MANAGEMENT_PASSWORD }}
  BP_RABBITMQ_MANAGEMENT_USERNAME: ${{ secrets.BP_RABBITMQ_MANAGEMENT_USERNAME }}
  BP_POSTGRES_USERNAME: ${{ secrets.BP_POSTGRES_USERNAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

  PODBEAN_CLIENT_SECRET_PRODUCTION: ${{ secrets.PODBEAN_CLIENT_SECRET_PRODUCTION }}
  PODBEAN_CLIENT_ID_PRODUCTION: ${{ secrets.PODBEAN_CLIENT_ID_PRODUCTION }}

  PODBEAN_CLIENT_SECRET_DEVELOPMENT: ${{ secrets.PODBEAN_CLIENT_SECRET_DEVELOPMENT }}
  PODBEAN_CLIENT_ID_DEVELOPMENT: ${{ secrets.PODBEAN_CLIENT_ID_DEVELOPMENT }}

  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15


      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - run: |-
          gcloud --quiet auth configure-docker

      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Setup gcloud environment
        uses: GoogleCloudPlatform/github-actions@0.1.2

      - name: Deploy to the cluster
        run: |
          cd $GITHUB_WORKSPACE
          export BP_MODE="DEVELOPMENT"
          if [ "$GITHUB_EVENT_NAME" = "create" ]; then
            if [[  "${GITHUB_REF}" =~ "tags" ]]; then
              BP_MODE="PRODUCTION"
            fi
          fi
          echo "BP_MODE=${BP_MODE}"
          cd $GITHUB_WORKSPACE
          ./deploy/deploy-gke/deploy.sh $BP_MODE