name: Deploy API


env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  CONFIGURATION_SERVER_USERNAME: ${{ secrets.CONFIGURATION_SERVER_USERNAME }}
  CONFIGURATION_SERVER_PASSWORD: ${{ secrets.CONFIGURATION_SERVER_PASSWORD }}
  GCLOUD_ZONE_DEVELOPMENT: ${{ secrets.GCLOUD_ZONE_DEVELOPMENT }}
  GCLOUD_ZONE_PRODUCTION: ${{ secrets.GCLOUD_ZONE_DEVELOPMENT }}
  GCLOUD_PROJECT_DEVELOPMENT: ${{ secrets.GCLOUD_PROJECT_DEVELOPMENT }}
  GCLOUD_PROJECT_PRODUCTION: ${{ secrets.GCLOUD_PROJECT_DEVELOPMENT }}
  GCLOUD_SA_KEY: ${{ secrets.GCLOUD_SA_KEY }}
  GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  CONFIGURATION_SERVER_URI_PRODUCTION: https://configuration.bootifulpodcast.fm
  CONFIGURATION_SERVER_URI_DEVELOPMENT: https://configuration.development.bootifulpodcast.fm
  GKE_CLUSTER_NAME_PRODUCTION: bootiful-podcast-production
  GKE_CLUSTER_NAME_DEVELOPMENT: bootiful-podcast-development

on:
  repository_dispatch:
    types: [ deploy-production-event, deploy-development-event ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - uses: bootiful-podcast/bp-mode-github-action@v34

      - uses: joshlong/config-client-github-action@v29
        with:
          config-server-uri: http://34.71.92.231
          config-server-username: ${{ secrets.CONFIGURATION_SERVER_USERNAME  }}
          config-server-password: ${{ secrets.CONFIGURATION_SERVER_PASSWORD  }}
          config-server-application-id: deployment
          config-server-profile: ${{ env.BP_MODE_LOWERCASE }}

      # - name: "Setup Initial Environment"
      #   run: |
      #     source $GITHUB_WORKSPACE/.github/workflows/bp_mode.sh

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          project_id: ${{ env.GCLOUD_PROJECT }}
          export_default_credentials: true

      - run: |-
          gcloud config set project $GCLOUD_PROJECT
          gcloud --quiet auth configure-docker

      - run: |
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone "$GCLOUD_ZONE" --project $GCLOUD_PROJECT


      - uses: joshlong/config-client-github-action@v29
        with:
          config-server-uri: http://34.71.92.231
          config-server-username: ${{ secrets.CONFIGURATION_SERVER_USERNAME  }}
          config-server-password: ${{ secrets.CONFIGURATION_SERVER_PASSWORD  }}
          config-server-application-id: deployment
          config-server-profile: ${{ env.BP_MODE_LOWERCASE }}

      # - name: Connect to Config Server for Configuration
      #   run: |
      #     source $GITHUB_WORKSPACE/.github/workflows/config_client.sh
      #     install_config_client_cli
      #     hydrate_environment_from_config_server

      - name: Deploy API
        run: |
          # source $GITHUB_WORKSPACE/.github/workflows/bp_mode.sh
          cd $GITHUB_WORKSPACE
          ./deploy/deploy.sh
